version: '3.9'
services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www
      - ./logs/apache:/var/log/apache2 # Logs de Apache
      - ./logs/php:/var/log/php        # Logs de PHP
      - ./docker/apache/vhost.conf:/etc/apache2/sites-available/vhost.conf # Archivo vhost.conf
    env_file:
      - .env
    environment:
      APP_ENV: ${APP_ENV}
      APP_DEBUG: ${APP_DEBUG}
      DB_CONNECTION: ${DB_CONNECTION}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      db:
        condition: service_healthy
    command: >
      /bin/bash -c "a2dissite 000-default.conf && a2ensite vhost.conf && apache2-foreground"

  db:
    image: mysql:8.0
    container_name: paco_libreria_db
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - db_data:/var/lib/mysql
      - ./src/migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u${DB_USERNAME}", "-p${DB_PASSWORD}"]
      interval: 30s
      timeout: 10s
      retries: 5

  test:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - ./src:/var/www
      - ./tests:/var/www/tests
      - ./phpunit.xml:/var/www/phpunit.xml
    working_dir: /var/www
    entrypoint: ["./vendor/bin/phpunit"]

volumes:
  db_data:
